"""incremento 2.3: fundacao do banco de dados cientifico

Revision ID: 4920cd8fd160
Revises: c32e9b0f0f3c
Create Date: 2026-08-08 01:54:36.325646

"""
import sqlalchemy as sa

from alembic import op

revision = '4920cd8fd160'
down_revision = 'c32e9b0f0f3c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_definitions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('canonical_key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('dimension', sa.String(length=100), nullable=False),
    sa.Column('canonical_unit', sa.String(length=50), nullable=False),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('applicable_domain', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_key')
    )
    op.create_table('scientific_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('source_type', sa.Enum('DATABASE', 'PUBLISHER', 'SUPPLIER', 'INSTITUTIONAL', 'OTHER', name='sourcetype', native_enum=False), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('publisher', sa.String(length=200), nullable=True),
    sa.Column('license', sa.String(length=200), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('terms_of_use', sa.Text(), nullable=True),
    sa.Column('accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('redistribution_status', sa.Enum('ALLOWED', 'PROHIBITED', 'UNKNOWN', name='redistributionstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suppliers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bibliographic_references',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('doi', sa.String(length=200), nullable=True),
    sa.Column('pmid', sa.String(length=50), nullable=True),
    sa.Column('other_identifier', sa.String(length=200), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('authors', sa.Text(), nullable=True),
    sa.Column('venue', sa.String(length=300), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('metadata_source_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['metadata_source_id'], ['scientific_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingestion_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('connector_name', sa.String(length=100), nullable=False),
    sa.Column('connector_version', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('received_count', sa.Integer(), nullable=False),
    sa.Column('created_count', sa.Integer(), nullable=False),
    sa.Column('updated_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('rejected_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'SUCCEEDED', 'PARTIAL', 'FAILED', name='ingestionstatus', native_enum=False), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('raw_payload_checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('audit_event_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audit_event_id'], ['audit_events.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['scientific_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scientific_entities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('entity_type', sa.Enum('BIOMATERIAL', 'CHEMICAL_SUBSTANCE', 'DRUG', 'FORMULATION', 'NANOMATERIAL', 'OTHER', name='scientificentitytype', native_enum=False), nullable=False),
    sa.Column('preferred_name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('review_status', sa.Enum('DRAFT', 'REVIEWED', 'REJECTED', 'DEPRECATED', name='curationstate', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('biological_evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('assay_type', sa.String(length=200), nullable=False),
    sa.Column('biological_model', sa.String(length=100), nullable=False),
    sa.Column('species', sa.String(length=150), nullable=True),
    sa.Column('cell_line', sa.String(length=150), nullable=True),
    sa.Column('organism', sa.String(length=150), nullable=True),
    sa.Column('endpoint', sa.String(length=200), nullable=False),
    sa.Column('result_value', sa.Float(), nullable=True),
    sa.Column('result_text', sa.Text(), nullable=True),
    sa.Column('dose_value', sa.Float(), nullable=True),
    sa.Column('dose_unit', sa.String(length=50), nullable=True),
    sa.Column('duration_value', sa.Float(), nullable=True),
    sa.Column('duration_unit', sa.String(length=50), nullable=True),
    sa.Column('conditions', sa.JSON(), nullable=True),
    sa.Column('reference_id', sa.String(length=36), nullable=True),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('research_classification_only', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['scientific_entities.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['reference_id'], ['bibliographic_references.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['scientific_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crystal_structure_references',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('database_name', sa.String(length=50), nullable=False),
    sa.Column('accession_id', sa.String(length=100), nullable=False),
    sa.Column('formula', sa.String(length=200), nullable=True),
    sa.Column('crystal_system', sa.String(length=50), nullable=True),
    sa.Column('space_group', sa.String(length=50), nullable=True),
    sa.Column('cell_params', sa.JSON(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('license', sa.String(length=200), nullable=True),
    sa.Column('file_checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['scientific_entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('database_name', 'accession_id', name='uq_crystal_structure_accession')
    )
    op.create_table('review_decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('subject_type', sa.String(length=100), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('decision', sa.Enum('APPROVED', 'REJECTED', 'CHANGES_REQUESTED', name='reviewdecisionoutcome', native_enum=False), nullable=False),
    sa.Column('reviewer_user_id', sa.String(length=36), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('previous_state', sa.String(length=50), nullable=True),
    sa.Column('new_state', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scientific_identifiers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('namespace', sa.String(length=50), nullable=False),
    sa.Column('identifier', sa.String(length=200), nullable=False),
    sa.Column('identifier_normalized', sa.String(length=200), nullable=False),
    sa.Column('verification_status', sa.Enum('UNVERIFIED', 'VERIFIED', 'DISPUTED', name='identifierverificationstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['scientific_entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('namespace', 'identifier_normalized', name='uq_identifier_namespace_normalized')
    )
    op.create_table('supplier_products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('supplier_id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('catalog_sku', sa.String(length=100), nullable=False),
    sa.Column('commercial_name', sa.String(length=300), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('lot_number', sa.String(length=100), nullable=True),
    sa.Column('registry_valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registry_valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('declared_properties', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['scientific_entities.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_id', 'catalog_sku', name='uq_supplier_product_sku')
    )
    op.create_table('property_observations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('property_definition_id', sa.String(length=36), nullable=False),
    sa.Column('value_numeric', sa.Float(), nullable=True),
    sa.Column('value_min', sa.Float(), nullable=True),
    sa.Column('value_max', sa.Float(), nullable=True),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('unit_original', sa.String(length=50), nullable=False),
    sa.Column('value_normalized', sa.Float(), nullable=True),
    sa.Column('method', sa.String(length=300), nullable=True),
    sa.Column('condition_temperature_k', sa.Float(), nullable=True),
    sa.Column('condition_pressure_kpa', sa.Float(), nullable=True),
    sa.Column('condition_ph', sa.Float(), nullable=True),
    sa.Column('condition_medium', sa.String(length=200), nullable=True),
    sa.Column('conditions_extra', sa.JSON(), nullable=True),
    sa.Column('uncertainty_low', sa.Float(), nullable=True),
    sa.Column('uncertainty_high', sa.Float(), nullable=True),
    sa.Column('evidence_type', sa.Enum('EXPERIMENTAL', 'CALCULATED', 'SUPPLIER_DECLARED', 'INFERRED', 'SYNTHETIC_DEMO', 'UNVERIFIED', name='evidencetype', native_enum=False), nullable=False),
    sa.Column('reference_id', sa.String(length=36), nullable=True),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('source_location', sa.String(length=200), nullable=True),
    sa.Column('related_supplier_product_id', sa.String(length=36), nullable=True),
    sa.Column('review_status', sa.Enum('DRAFT', 'REVIEWED', 'REJECTED', 'DEPRECATED', name='curationstate', native_enum=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('dedup_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['scientific_entities.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['property_definition_id'], ['property_definitions.id'], ),
    sa.ForeignKeyConstraint(['reference_id'], ['bibliographic_references.id'], ),
    sa.ForeignKeyConstraint(['related_supplier_product_id'], ['supplier_products.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['scientific_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedup_fingerprint', name='uq_property_observation_fingerprint')
    )
    op.add_column('material_records', sa.Column('scientific_entity_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(
        'fk_material_records_scientific_entity_id', 'material_records', 'scientific_entities', ['scientific_entity_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_material_records_scientific_entity_id', 'material_records', type_='foreignkey')
    op.drop_column('material_records', 'scientific_entity_id')
    op.drop_table('property_observations')
    op.drop_table('supplier_products')
    op.drop_table('scientific_identifiers')
    op.drop_table('review_decisions')
    op.drop_table('crystal_structure_references')
    op.drop_table('biological_evidence')
    op.drop_table('scientific_entities')
    op.drop_table('ingestion_runs')
    op.drop_table('bibliographic_references')
    op.drop_table('suppliers')
    op.drop_table('scientific_sources')
    op.drop_table('property_definitions')
    # ### end Alembic commands ###
