"""incremento 2.3 rodada 2: infraestrutura de ingestao e conector pubchem

Revision ID: 511279411501
Revises: 4920cd8fd160
Create Date: 2026-08-08 11:03:43.339694

"""
import sqlalchemy as sa

from alembic import op

revision = '511279411501'
down_revision = '4920cd8fd160'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_source_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('connector_id', sa.String(length=100), nullable=False),
    sa.Column('connector_version', sa.String(length=50), nullable=False),
    sa.Column('external_record_id', sa.String(length=200), nullable=False),
    sa.Column('requested_endpoint', sa.String(length=500), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('payload_sha256', sa.String(length=64), nullable=False),
    sa.Column('payload_size_bytes', sa.Integer(), nullable=False),
    sa.Column('schema_mapping_version', sa.String(length=50), nullable=False),
    sa.Column('predecessor_record_id', sa.String(length=36), nullable=True),
    sa.Column('parsing_status', sa.Enum('PARSED', 'PARTIAL', 'FAILED', name='parsingstatus', native_enum=False), nullable=False),
    sa.Column('parsing_error', sa.JSON(), nullable=True),
    sa.Column('retention_policy', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['predecessor_record_id'], ['raw_source_records.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['scientific_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_raw_source_records_source_external_id', 'raw_source_records', ['source_id', 'external_record_id'], unique=False)
    op.create_table('scientific_ingestion_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('requested_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('connector_id', sa.String(length=100), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('external_ids', sa.JSON(), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCEEDED', 'PARTIAL', 'FAILED', 'CANCELLED', name='ingestionrequeststatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claimed_by_dispatcher_id', sa.String(length=200), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('cancel_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('error', sa.JSON(), nullable=True),
    sa.Column('correlation_id', sa.String(length=36), nullable=False),
    sa.Column('ingestion_run_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['scientific_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scientific_ingestion_requests_status_created_at', 'scientific_ingestion_requests', ['status', 'created_at'], unique=False)
    op.create_table('ingestion_conflicts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ingestion_request_id', sa.String(length=36), nullable=False),
    sa.Column('external_record_id', sa.String(length=200), nullable=False),
    sa.Column('conflict_type', sa.Enum('INCHIKEY_SHARED_WITH_OTHER_ENTITY', 'IDENTIFIER_VERIFICATION_DISPUTED', 'OTHER', name='ingestionconflicttype', native_enum=False), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('other_entity_id', sa.String(length=36), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['scientific_entities.id'], ),
    sa.ForeignKeyConstraint(['ingestion_request_id'], ['scientific_ingestion_requests.id'], ),
    sa.ForeignKeyConstraint(['other_entity_id'], ['scientific_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('property_observations', sa.Column('raw_source_record_id', sa.String(length=36), nullable=True))
    # Nome explicito da FK (autogenerate deixa None, o que quebra drop_constraint(None, ...) no
    # downgrade -- bug recorrente ja visto nas rodadas anteriores deste incremento).
    op.create_foreign_key(
        'fk_property_observations_raw_source_record_id', 'property_observations', 'raw_source_records',
        ['raw_source_record_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_property_observations_raw_source_record_id', 'property_observations', type_='foreignkey')
    op.drop_column('property_observations', 'raw_source_record_id')
    op.drop_table('ingestion_conflicts')
    op.drop_index('ix_scientific_ingestion_requests_status_created_at', table_name='scientific_ingestion_requests')
    op.drop_table('scientific_ingestion_requests')
    op.drop_index('ix_raw_source_records_source_external_id', table_name='raw_source_records')
    op.drop_table('raw_source_records')
    # ### end Alembic commands ###
