"""adiciona expires_at em operational_states (suite clinica, incremento 1.1)

Revision ID: 9242186001a8
Revises: 927e185f097d
Create Date: 2026-07-28 00:14:18.634769

"""
import sqlalchemy as sa

from alembic import op

revision = '9242186001a8'
down_revision = '927e185f097d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operational_states', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operational_states', 'expires_at')
    # ### end Alembic commands ###
