"""modelos do incremento 2.1: materiais, projeto, receita, job, artefatos

Revision ID: 97983fbc0288
Revises: 9242186001a8
Create Date: 2026-07-29 11:23:49.044564

"""
import sqlalchemy as sa

from alembic import op

revision = '97983fbc0288'
down_revision = '9242186001a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('source_type', sa.Enum('SYNTHETIC', 'LITERATURE', name='materialsourcetype', native_enum=False), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('review_status', sa.Enum('DRAFT', 'REVIEWED', 'DEPRECATED', name='reviewstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('biomat_projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('owner_user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='projectstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scientific_references',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('material_id', sa.String(length=36), nullable=False),
    sa.Column('citation_text', sa.Text(), nullable=False),
    sa.Column('doi', sa.String(length=200), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('source_document', sa.String(length=300), nullable=True),
    sa.Column('page_reference', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['material_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('geometry_recipes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('schema_version', sa.String(length=20), nullable=False),
    sa.Column('canonical_json', sa.JSON(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_recipe_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'VALIDATED', name='recipestatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['parent_recipe_id'], ['geometry_recipes.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['biomat_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material_properties',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('material_id', sa.String(length=36), nullable=False),
    sa.Column('property_name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=300), nullable=False),
    sa.Column('reference_id', sa.String(length=36), nullable=True),
    sa.Column('method', sa.String(length=300), nullable=True),
    sa.Column('uncertainty_low', sa.Float(), nullable=True),
    sa.Column('uncertainty_high', sa.Float(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('review_status', sa.Enum('DRAFT', 'REVIEWED', 'DEPRECATED', name='reviewstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['material_records.id'], ),
    sa.ForeignKeyConstraint(['reference_id'], ['scientific_references.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('design_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('recipe_id', sa.String(length=36), nullable=False),
    sa.Column('material_id', sa.String(length=36), nullable=True),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['material_records.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['biomat_projects.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['geometry_recipes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'idempotency_key', name='uq_design_run_org_idempotency')
    )
    op.create_table('geometry_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('design_run_id', sa.String(length=36), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED', name='jobstatus', native_enum=False), nullable=False),
    sa.Column('progress_pct', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('worker_version', sa.String(length=50), nullable=True),
    sa.Column('dotnet_version', sa.String(length=50), nullable=True),
    sa.Column('picogk_version', sa.String(length=50), nullable=True),
    sa.Column('hardware_info', sa.JSON(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('cancelled_by_user_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['cancelled_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['design_run_id'], ['design_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artifact_manifests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('geometry_job_id', sa.String(length=36), nullable=False),
    sa.Column('manifest_json', sa.JSON(), nullable=False),
    sa.Column('manifest_sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['geometry_job_id'], ['geometry_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('geometry_job_id')
    )
    op.create_table('artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('geometry_job_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.Enum('STL', 'VDB', 'THUMBNAIL', 'MANIFEST', 'LOG', name='artifactkind', native_enum=False), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['geometry_job_id'], ['geometry_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artifacts')
    op.drop_table('artifact_manifests')
    op.drop_table('geometry_jobs')
    op.drop_table('design_runs')
    op.drop_table('material_properties')
    op.drop_table('geometry_recipes')
    op.drop_table('scientific_references')
    op.drop_table('biomat_projects')
    op.drop_table('material_records')
    # ### end Alembic commands ###
