"""incremento 2.1.1: claim atomico e cancelamento real de geometry_jobs

Revision ID: c32e9b0f0f3c
Revises: 97983fbc0288
Create Date: 2026-07-29 13:27:17.204373

"""
import sqlalchemy as sa

from alembic import op

revision = 'c32e9b0f0f3c'
down_revision = '97983fbc0288'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('geometry_jobs', sa.Column('claimed_by_dispatcher_id', sa.String(length=200), nullable=True))
    op.add_column('geometry_jobs', sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('geometry_jobs', sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('geometry_jobs', sa.Column('cancel_requested_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('geometry_jobs', sa.Column('worker_pid', sa.Integer(), nullable=True))
    op.create_index('ix_geometry_jobs_status_created_at', 'geometry_jobs', ['status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_geometry_jobs_status_created_at', table_name='geometry_jobs')
    op.drop_column('geometry_jobs', 'worker_pid')
    op.drop_column('geometry_jobs', 'cancel_requested_at')
    op.drop_column('geometry_jobs', 'heartbeat_at')
    op.drop_column('geometry_jobs', 'claimed_at')
    op.drop_column('geometry_jobs', 'claimed_by_dispatcher_id')
    # ### end Alembic commands ###
